### ISSUE TITLE
Plugin breaks page rendering

### ISSUE THREAD

**Issue by Allaman** [Sommerregen/grav-plugin-smileys#11]
With plugin enabled:

![enabled](https://user-images.githubusercontent.com/12184268/39965574-14e571a8-569c-11e8-8cb1-3967ea300e1a.png)

With plugin disabled:
![disabled](https://user-images.githubusercontent.com/12184268/39965577-2df0c210-569c-11e8-8572-b624d14a394b.png)

Markdown source file:
`There are quite a lot of options [how to install a kubernetes cluster](https://kubernetes.io/docs/setup/pick-right-solution/). `

Version:

Grav 1.4.4
Plugin: 1.2.1

**Comment by Sommerregen** [comment]
Hi @Allaman ,

can you show me the source code, too? Sometimes the debugger show things differently than there are in real.

**Comment by Allaman** [comment]
Hi @Sommerregen ,

sure :)

```html
<h2 id="installation-on-a-bare-metal..." class="headeranchor"><a class="headeranchor-link headeranchor-link--left headeranchor-visible--hover" aria-hidden="true" href="#installation-on-a-bare-metal..." title="Permanent link: Installation on a "bare metal" single Node" data-icon="#">Installation on a "bare metal" single Node</a></h2>
<p>There are quite a lot of options <a href="https&lt;img title=" unsure="" :="" alt=":" class="smileys" src="/user/data/smileys/simple_smileys/unsure.png"></a>//kubernetes.io/docs/setup/pick-right-solution/"&gt;how to install a kubernetes cluster. </p>
```
